### PR TITLE
Draft: Server handler seperation

### PR DESCRIPTION
**Pull request by mellonnen**
This is a restructuring of the code in order to be able to expose logic for testing that was previously hidden on the HTTP handler (see #24).

We now have a `CIServer` and a `CIServerHandler`. We define functionality that we want to test on the `CIServer` and pass those methods as functions to the `CIServerHandler` so it can be used in the `do_POST` and `do_GET` methods

for instance, if we wanted to test the `update_commit_status` method we would something like this

```python
server = CIServer("localhost", 8080)
# without starting the server
assert(server.update_commit_status("master", False) == False)
...
```

### CODE REVIEW

**Comment by PersonligaPersson** [comment]
Tried installing an ubuntu machine. Had errors for the package GDAL 3.4.1. Will try on another system.

**Comment by PersonligaPersson** [comment]
> Tried installing an ubuntu machine. Had errors for the package GDAL 3.4.1. Will try on another system.

After testing to install the requirements on a windows computer I also get error messages, however this time with a package called Kiwisolver. This suggests to me that the error is not with the pull request but with my setup. Will investigate further.

**Comment by mellonnen** [comment]
I created a new environment and only pip installed PyGithub and pytest, I think it removed the dependencies you talked about. I think I have accidentally installed other stuff.

**Comment by PersonligaPersson** [comment]
Aftear cleanup the requirements now installs properly.

**Comment by PersonligaPersson** [comment]
Alright now I'm able to run the server and access it locally. The current state looks good to me. Let's get someone else's eyes on this as well before merging.

**Pull request merged**
